version: '3.9'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - "8000:8000"
      - "${PORT}:${PORT}"